spring:
  datasource:
    name: druidDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: yfyfyf
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mariadb://10.135.37.130:3306/powerProphet?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowMultiQueries=true
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    username: 1186599081@qq.com
    password: tswohohzeghgiifi
    properties:
      mail:
        smtp:
          ssl:
            enable: true
            required: false
  data:
    redis:
      host: 10.135.37.130
      port: 6379
      password: yfyfyf
      database: 0
      lettuce:
        pool:
          max-idle: 16
          max-active: 32
          min-idle: 8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
server:
  port: 8081