spring:
  datasource:
    name: druidDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mariadb://127.0.0.1:3306/powerProphet?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowMultiQueries=true
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    username: 1186599081@qq.com
    password: 123445
    properties:
      mail:
        smtp:
          ssl:
            enable: true
            required: false
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      database: 0
      lettuce:
        pool:
          max-idle: 16
          max-active: 32
          min-idle: 8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
server:
  port: 8081
#  port: 8099
